import { api } from '@/lib/apiClient';

export type QuestionContentType = 'TEXT' | 'IMAGE' | 'VIDEO' | 'URL';

/**
 * What SHAPE a question is — the type dropdown on the form. MCQ is the
 * default and what every question authored before it existed means.
 * LINEAR_SCALE's options are GENERATED by the backend (the points 1—5) and
 * are never authored here; LIKERT_GRID is not built yet.
 */
export type QuestionType = 'MCQ' | 'LINEAR_SCALE' | 'LIKERT_GRID' | 'SHORT_ANSWER' | 'PARAGRAPH';

/**
 * What a linear scale means when nobody says otherwise — every scale authored
 * before the range existed. Mirrors DEFAULT_SCALE_FROM/TO on the backend.
 */
export const DEFAULT_SCALE_FROM = 1;
export const DEFAULT_SCALE_TO = 5;

/**
 * Not a design limit — any range is allowed, negative ones included. This
 * catches a TYPO: the points are stored as real option rows, so "1 to
 * 1000000" would be a million-row insert. Mirrors MAX_SCALE_POINTS.
 */
export const MAX_SCALE_POINTS = 1000;

export const QUESTION_TYPES: Array<{ value: QuestionType; label: string; hint: string }> = [
  { value: 'MCQ', label: 'Multiple choice (MCQ)', hint: 'Options you write, each scored against MQTs.' },
  {
    value: 'LINEAR_SCALE',
    label: 'Linear scale',
    hint: 'A range you choose, with a label at each end. Respondents drag a slider; the point they land on is the score, so only the question is mapped to MQTs.',
  },
  {
    value: 'LIKERT_GRID',
    label: 'Likert scale (grid)',
    hint: 'Rows are the statements, columns the shared rating scale. Each row names the MQTs it measures; the columns carry the scores. One pick per row.',
  },
  {
    value: 'SHORT_ANSWER',
    label: 'Short answer',
    hint: 'Respondents type an answer. Nothing to pick, so nothing to score per option — a question-level MQT score, if you set one, is earned for answering.',
  },
  // PARAGRAPH is in the backend enum but not offered: nothing may write it
  // until the long-answer UI exists.
];

/**
 * How many options the respondent may pick, read with selectionCount:
 * MIN = at least n, MAX = up to n, EQUALS = exactly n. Null rule (and null
 * count — the two always travel together) is single choice.
 */
export type SelectionRule = 'MIN' | 'MAX' | 'EQUALS';

/** The floor and cap a (rule, count) pair resolves to. Mirrors SelectionBounds. */
export function selectionBounds(
  rule: SelectionRule | null,
  count: number | null,
  optionCount: number,
): { floor: number; cap: number } {
  if (rule == null || count == null) return { floor: 1, cap: 1 };
  if (rule === 'EQUALS') return { floor: count, cap: count };
  if (rule === 'MAX') return { floor: 1, cap: count };
  return { floor: count, cap: Math.max(count, optionCount) };
}

/** "Select exactly 2 of 5" — one wording, used by the form and the upload review. */
export function selectionLabel(
  rule: SelectionRule | null,
  count: number | null,
  optionCount: number,
): string {
  if (rule == null || count == null) return 'Single choice';
  const of = ` of ${optionCount}`;
  if (rule === 'EQUALS') return `Select exactly ${count}${of}`;
  if (rule === 'MAX') return `Select at most ${count}${of}`;
  return `Select at least ${count}${of}`;
}

// ── Wire shapes — mirror spring-social's DTOs 1:1 ──────────────────────────
/**
 * Matches MqtScoreRequest on the backend.
 *
 * `score` is decimal (0.25, 0.5, 2.75 …), stored to two places — the backend
 * rounds to 2 on write, so send what the author typed and read back what it
 * kept.
 */
export interface MqtScorePayload {
  measuredQualityTypeId: number;
  score: number;
}

/** Matches MqtScoreResponse on the backend. */
export interface MqtScoreView {
  measuredQualityTypeId: number;
  measuredQualityTypeName: string;
  score: number;
}

/** Matches QuestionOptionRequest on the backend; list order = display order. */
export interface QuestionOptionPayload {
  optionText: string | null;
  /**
   * Optional help text shown under this option's label in the portal. Null
   * when the author left the description box unticked or empty.
   */
  description: string | null;
  contentType: QuestionContentType;
  mediaUrl: string | null;
  mqtScores: MqtScorePayload[];
}

/**
 * Matches QuestionRequest on the backend. Questions are standalone bank
 * items — attaching them to a questionnaire is a separate flow.
 */
export interface QuestionPayload {
  contentType: QuestionContentType;
  questionType: QuestionType;
  stem: string;
  /**
   * Optional help text shown under the stem in the portal — "answer for the
   * last two weeks". Null when the author left the description box unticked
   * or empty.
   */
  description: string | null;
  mediaUrl: string | null;
  riskFlag: boolean;
  /** Both null = single choice. The backend rejects one without the other. */
  selectionRule: SelectionRule | null;
  selectionCount: number | null;
  /**
   * MCQ only — deliver the options in a random order, seeded per attempt, so
   * two respondents meet the choices differently. The backend REFUSES it on a
   * LINEAR_SCALE (ordinal points) and a LIKERT_GRID (shared rating scale).
   */
  shuffleOptions: boolean;
  /**
   * LINEAR_SCALE only — the inclusive range the author chose. Both or
   * neither; both omitted means 1—5. Negative ends are allowed (a bipolar
   * -3—3 scores negatively, which is the point of one).
   */
  scaleFrom: number | null;
  scaleTo: number | null;
  /** LINEAR_SCALE only — the captions under the first and last point. */
  scaleLowLabel: string | null;
  scaleHighLabel: string | null;
  /**
   * Ignored on a LINEAR_SCALE: the backend generates the points instead.
   * On a LIKERT_GRID these are the shared COLUMNS. A SHORT_ANSWER has none.
   */
  options: QuestionOptionPayload[];
  /** LIKERT_GRID only — the statements. Ignored on every other type. */
  rows: QuestionRowPayload[];
  mqtScores: MqtScorePayload[];
}

/**
 * Matches QuestionRowRequest on the backend — one row of a LIKERT_GRID.
 * The MQT ids are a NOMINATION with no scores: the number a rating is worth
 * comes from the column, which is scored like any MCQ option.
 */
export interface QuestionRowPayload {
  rowText: string | null;
  measuredQualityTypeIds: number[];
}

/** Matches MqtRefResponse on the backend — an MQT named without a score. */
export interface MqtRef {
  measuredQualityTypeId: number;
  measuredQualityTypeName: string;
}

/** Matches QuestionRowResponse on the backend. Empty on non-grid questions. */
export interface QuestionRowResponse {
  questionRowId: number;
  rowText: string | null;
  sortOrder: number;
  mqts: MqtRef[];
}

/** Matches QuestionOptionResponse on the backend. */
export interface QuestionOptionResponse {
  optionId: number;
  optionText: string | null;
  /** Help text under the label; null when the author set none. */
  description: string | null;
  contentType: QuestionContentType;
  mediaUrl: string | null;
  sortOrder: number;
  mqtScores: MqtScoreView[];
}

/** One questionnaire that uses a bank question. */
export interface UsedInRef {
  questionnaireId: number;
  name: string;
}

/**
 * Matches QuestionResponse on the backend. usedIn lists every questionnaire
 * the question appears in (empty = unattached). sectionId/sortOrder/
 * questionTag are only set when reading through one questionnaire
 * (getByQuestionnaireId) — they are that questionnaire's placement,
 * meaningless in bank-wide reads. questionTag is the placement's report
 * identifier ("Section_A_Q_1" / "Q_1"), stamped by the questions PUT; null
 * on placements saved before tags existed.
 */
export interface QuestionResponse {
  questionId: number;
  usedIn: UsedInRef[];
  sectionId: number | null;
  sortOrder: number | null;
  questionTag: string | null;
  contentType: QuestionContentType;
  questionType: QuestionType;
  stem: string;
  /** Help text under the stem; null when the author set none. */
  description: string | null;
  mediaUrl: string | null;
  riskFlag: boolean;
  selectionRule: SelectionRule | null;
  selectionCount: number | null;
  /**
   * Delivery order only: `options` below is ALWAYS the authored order, here
   * and in every preview. The randomising happens per attempt in the portal
   * payload, so nothing on the dashboard can show what one respondent saw.
   */
  shuffleOptions: boolean;
  /** LINEAR_SCALE only, and always both — stored resolved, so never half-set. */
  scaleFrom: number | null;
  scaleTo: number | null;
  scaleLowLabel: string | null;
  scaleHighLabel: string | null;
  /** On a LINEAR_SCALE these are the generated points, carrying derived scores. */
  options: QuestionOptionResponse[];
  /** LIKERT_GRID only — empty everywhere else. */
  rows: QuestionRowResponse[];
  mqtScores: MqtScoreView[];
}

//question apis
function getAllQuestions() {
  return api.get<QuestionResponse[]>(`/questions/getAll`);
}

function getQuestionById(id: number) {
  return api.get<QuestionResponse>(`/questions/getById/${id}`);
}

function createQuestion(question: QuestionPayload) {
  return api.post<QuestionResponse>(`/questions/create`, question);
}

/** All-or-nothing: the backend validates every item before writing any. */
function bulkCreateQuestions(questions: QuestionPayload[]) {
  return api.post<QuestionResponse[]>(`/questions/bulk-create`, questions);
}

function updateQuestion(id: number, question: QuestionPayload) {
  return api.put<QuestionResponse>(`/questions/update/${id}`, question);
}

function deleteQuestion(id: number) {
  return api.delete<void>(`/questions/delete/${id}`);
}

//question wrt questionnaire apis
function getQuestionsByQuestionnaireId(questionnaireId: number) {
  return api.get<QuestionResponse[]>(`/questions/getByQuestionnaireId/${questionnaireId}`);
}


export const questionApis = {
  getAllQuestions,
  getQuestionById,
  createQuestion,
  bulkCreateQuestions,
  updateQuestion,
  deleteQuestion,
  getQuestionsByQuestionnaireId,
};
