-- V1 — baseline: the full schema as the current entity model defines it.
--
-- Generated from a database Hibernate built from the entities, so it matches
-- the mappings exactly (one allotment per respondent+assessment, answers and
-- demographic responses parented to that pair, no attemptNumber).
--
-- Runs on an EMPTY database to create everything. On a database that already
-- holds this schema, spring.flyway.baseline-on-migrate stamps it at version 1
-- and skips this file — so both a fresh install and an existing environment
-- end up at the same point and pick up V2 onward.
--
-- Do not edit this file once it has run anywhere: Flyway checksums applied
-- migrations and a change fails every later startup. Corrections go in a new
-- V<n> script.

SET FOREIGN_KEY_CHECKS = 0;

CREATE TABLE `User` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `account_status` bit(1) DEFAULT NULL,
  `dob` date NOT NULL,
  `email` varchar(255) NOT NULL,
  `last_login_at` datetime(6) DEFAULT NULL,
  `serial_id` varchar(20) DEFAULT NULL,
  `is_super_admin` bit(1) NOT NULL,
  `role_group_id` bigint DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uqUserEmail` (`email`),
  UNIQUE KEY `uqUserSerialId` (`serial_id`),
  KEY `fkUserRoleGroup` (`role_group_id`),
  CONSTRAINT `fkUserRoleGroup` FOREIGN KEY (`role_group_id`) REFERENCES `role_group` (`role_group_id`)
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `assessment` (
  `assessment_id` bigint NOT NULL AUTO_INCREMENT,
  `auto_next` bit(1) NOT NULL,
  `name` varchar(200) NOT NULL,
  `show_terms_and_conditions` bit(1) NOT NULL,
  `status` enum('ACTIVE','INACTIVE') NOT NULL,
  `questionnaire_id` bigint NOT NULL,
  PRIMARY KEY (`assessment_id`),
  KEY `idxAssessmentQuestionnaire` (`questionnaire_id`),
  CONSTRAINT `fkAssessmentQuestionnaire` FOREIGN KEY (`questionnaire_id`) REFERENCES `questionnaire` (`questionnaire_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `assessment_answer` (
  `assessment_answer_id` bigint NOT NULL AUTO_INCREMENT,
  `answer_text` text,
  `rank_order` int DEFAULT NULL,
  `assessment_id` bigint NOT NULL,
  `option_id` bigint DEFAULT NULL,
  `question_id` bigint NOT NULL,
  `respondent_user_id` bigint NOT NULL,
  PRIMARY KEY (`assessment_answer_id`),
  UNIQUE KEY `uqAaRespondentAssessmentQuestionOption` (`respondent_user_id`,`assessment_id`,`question_id`,`option_id`),
  KEY `idxAaAssessment` (`assessment_id`),
  KEY `idxAaQuestion` (`question_id`),
  KEY `idxAaOption` (`option_id`),
  CONSTRAINT `fkAaAssessment` FOREIGN KEY (`assessment_id`) REFERENCES `assessment` (`assessment_id`),
  CONSTRAINT `fkAaOption` FOREIGN KEY (`option_id`) REFERENCES `question_option` (`option_id`),
  CONSTRAINT `fkAaQuestion` FOREIGN KEY (`question_id`) REFERENCES `question` (`question_id`),
  CONSTRAINT `fkAaRespondent` FOREIGN KEY (`respondent_user_id`) REFERENCES `respondent_user` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `demographic_field` (
  `demographic_field_id` bigint NOT NULL AUTO_INCREMENT,
  `field_type` enum('DATE','DROPDOWN','NUMBER','TEXT') NOT NULL,
  `label` varchar(150) NOT NULL,
  `placeholder` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`demographic_field_id`),
  UNIQUE KEY `uqDemographicFieldLabel` (`label`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `demographic_field_option` (
  `demographic_field_id` bigint NOT NULL,
  `option_value` varchar(255) NOT NULL,
  `sort_order` int NOT NULL,
  PRIMARY KEY (`demographic_field_id`,`sort_order`),
  CONSTRAINT `fkDemographicFieldOptionField` FOREIGN KEY (`demographic_field_id`) REFERENCES `demographic_field` (`demographic_field_id`),
  CONSTRAINT `demographic_field_option_chk_1` CHECK ((`sort_order` >= 0))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `demographic_response` (
  `demographic_response_id` bigint NOT NULL AUTO_INCREMENT,
  `response_value` text NOT NULL,
  `assessment_id` bigint NOT NULL,
  `demographic_field_id` bigint NOT NULL,
  `respondent_user_id` bigint NOT NULL,
  PRIMARY KEY (`demographic_response_id`),
  UNIQUE KEY `uqDrRespondentAssessmentField` (`respondent_user_id`,`assessment_id`,`demographic_field_id`),
  KEY `idxDrAssessment` (`assessment_id`),
  KEY `idxDrField` (`demographic_field_id`),
  CONSTRAINT `fkDrAssessment` FOREIGN KEY (`assessment_id`) REFERENCES `assessment` (`assessment_id`),
  CONSTRAINT `fkDrField` FOREIGN KEY (`demographic_field_id`) REFERENCES `demographic_field` (`demographic_field_id`),
  CONSTRAINT `fkDrRespondent` FOREIGN KEY (`respondent_user_id`) REFERENCES `respondent_user` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `languages` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `code` varchar(255) NOT NULL,
  `name` varchar(255) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `UKmyc139vxcejowe4q8qm3ca5jn` (`code`),
  UNIQUE KEY `UKf6axmaokhmrbmm746866v0uyu` (`name`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `measured_quality` (
  `measured_quality_id` bigint NOT NULL AUTO_INCREMENT,
  `description` text,
  `name` varchar(150) NOT NULL,
  PRIMARY KEY (`measured_quality_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `measured_quality_type` (
  `measured_quality_type_id` bigint NOT NULL AUTO_INCREMENT,
  `description` text,
  `name` varchar(150) NOT NULL,
  `sort_order` int NOT NULL,
  `measured_quality_id` bigint NOT NULL,
  `parent_type_id` bigint DEFAULT NULL,
  PRIMARY KEY (`measured_quality_type_id`),
  KEY `idxMqtMeasuredQuality` (`measured_quality_id`),
  KEY `idxMqtParent` (`parent_type_id`),
  CONSTRAINT `fkMqtMeasuredQuality` FOREIGN KEY (`measured_quality_id`) REFERENCES `measured_quality` (`measured_quality_id`),
  CONSTRAINT `fkMqtParent` FOREIGN KEY (`parent_type_id`) REFERENCES `measured_quality_type` (`measured_quality_type_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `option_mqt_score` (
  `option_mqt_score_id` bigint NOT NULL AUTO_INCREMENT,
  `score` int NOT NULL,
  `measured_quality_type_id` bigint NOT NULL,
  `option_id` bigint NOT NULL,
  PRIMARY KEY (`option_mqt_score_id`),
  UNIQUE KEY `uqOmsOptionMqt` (`option_id`,`measured_quality_type_id`),
  KEY `idxOmsMqt` (`measured_quality_type_id`),
  CONSTRAINT `fkOmsMqt` FOREIGN KEY (`measured_quality_type_id`) REFERENCES `measured_quality_type` (`measured_quality_type_id`),
  CONSTRAINT `fkOmsOption` FOREIGN KEY (`option_id`) REFERENCES `question_option` (`option_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `organization` (
  `organization_id` bigint NOT NULL AUTO_INCREMENT,
  `description` text,
  `name` varchar(200) NOT NULL,
  `org_email` varchar(200) DEFAULT NULL,
  PRIMARY KEY (`organization_id`),
  UNIQUE KEY `uqOrganizationName` (`name`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `organization_assessment_mapping` (
  `organization_assessment_mapping_id` bigint NOT NULL AUTO_INCREMENT,
  `mapped_at` datetime(6) NOT NULL,
  `assessment_id` bigint NOT NULL,
  `organization_id` bigint NOT NULL,
  PRIMARY KEY (`organization_assessment_mapping_id`),
  UNIQUE KEY `uqOamOrganizationAssessment` (`organization_id`,`assessment_id`),
  KEY `idxOamAssessment` (`assessment_id`),
  CONSTRAINT `fkOamAssessment` FOREIGN KEY (`assessment_id`) REFERENCES `assessment` (`assessment_id`),
  CONSTRAINT `fkOamOrganization` FOREIGN KEY (`organization_id`) REFERENCES `organization` (`organization_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `practitioner_user` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `name` varchar(255) DEFAULT NULL,
  `phone` varchar(255) DEFAULT NULL,
  `practitioner_status` enum('ACTIVE','INACTIVE','SUSPENDED') NOT NULL,
  `vertical` enum('CLINICAL','COUNSELLING','EXPERIMENTS','INDUSTRIAL','OTHER','RESEARCH','WHITELABEL') DEFAULT NULL,
  `organization_id` bigint DEFAULT NULL,
  `user_id` bigint NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uqPractitionerUserUser` (`user_id`),
  KEY `fkPractitionerUserOrganization` (`organization_id`),
  CONSTRAINT `fkPractitionerUserOrganization` FOREIGN KEY (`organization_id`) REFERENCES `organization` (`organization_id`),
  CONSTRAINT `fkPractitionerUserUser` FOREIGN KEY (`user_id`) REFERENCES `User` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `question` (
  `question_id` bigint NOT NULL AUTO_INCREMENT,
  `content_type` enum('IMAGE','TEXT','URL','VIDEO') NOT NULL,
  `irta` double DEFAULT NULL,
  `irtb` double DEFAULT NULL,
  `irtc` double DEFAULT NULL,
  `media_url` text,
  `stem` text,
  `risk_flag` bit(1) NOT NULL,
  `risk_rule` text,
  `sub_domain` varchar(150) DEFAULT NULL,
  PRIMARY KEY (`question_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `question_mqt_score` (
  `question_mqt_score_id` bigint NOT NULL AUTO_INCREMENT,
  `score` int NOT NULL,
  `measured_quality_type_id` bigint NOT NULL,
  `question_id` bigint NOT NULL,
  PRIMARY KEY (`question_mqt_score_id`),
  UNIQUE KEY `uqQmsQuestionMqt` (`question_id`,`measured_quality_type_id`),
  KEY `idxQmsMqt` (`measured_quality_type_id`),
  CONSTRAINT `fkQmsMqt` FOREIGN KEY (`measured_quality_type_id`) REFERENCES `measured_quality_type` (`measured_quality_type_id`),
  CONSTRAINT `fkQmsQuestion` FOREIGN KEY (`question_id`) REFERENCES `question` (`question_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `question_option` (
  `option_id` bigint NOT NULL AUTO_INCREMENT,
  `content_type` enum('IMAGE','TEXT','URL','VIDEO') NOT NULL,
  `media_url` text,
  `option_text` text,
  `sort_order` int NOT NULL,
  `question_id` bigint NOT NULL,
  PRIMARY KEY (`option_id`),
  KEY `fkQuestionOptionQuestion` (`question_id`),
  CONSTRAINT `fkQuestionOptionQuestion` FOREIGN KEY (`question_id`) REFERENCES `question` (`question_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `questionnaire` (
  `questionnaire_id` bigint NOT NULL AUTO_INCREMENT,
  `is_adaptive` bit(1) NOT NULL,
  `age_range` varchar(50) DEFAULT NULL,
  `category` varchar(100) DEFAULT NULL,
  `description` text,
  `duration_minutes` int DEFAULT NULL,
  `is_fixed_sequence` bit(1) NOT NULL,
  `general_instruction` text,
  `has_sections` bit(1) NOT NULL,
  `name` varchar(200) NOT NULL,
  `norm_status` varchar(50) DEFAULT NULL,
  `scoring_model` varchar(32) DEFAULT NULL,
  `short_name` varchar(50) DEFAULT NULL,
  `tier_required` varchar(50) DEFAULT NULL,
  `uses_weighted_scoring` bit(1) NOT NULL,
  `vertical` enum('CLINICAL','COUNSELLING','EXPERIMENTS','INDUSTRIAL','OTHER','RESEARCH','WHITELABEL') DEFAULT NULL,
  PRIMARY KEY (`questionnaire_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `questionnaire_demographic_field` (
  `questionnaire_demographic_field_id` bigint NOT NULL AUTO_INCREMENT,
  `is_required` bit(1) NOT NULL,
  `sort_order` int NOT NULL,
  `demographic_field_id` bigint NOT NULL,
  `questionnaire_id` bigint NOT NULL,
  PRIMARY KEY (`questionnaire_demographic_field_id`),
  UNIQUE KEY `uqQdfQuestionnaireField` (`questionnaire_id`,`demographic_field_id`),
  KEY `idxQdfField` (`demographic_field_id`),
  CONSTRAINT `fkQdfField` FOREIGN KEY (`demographic_field_id`) REFERENCES `demographic_field` (`demographic_field_id`),
  CONSTRAINT `fkQdfQuestionnaire` FOREIGN KEY (`questionnaire_id`) REFERENCES `questionnaire` (`questionnaire_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `questionnaire_question` (
  `questionnaire_question_id` bigint NOT NULL AUTO_INCREMENT,
  `question_tag` varchar(50) DEFAULT NULL,
  `sort_order` int NOT NULL,
  `question_id` bigint NOT NULL,
  `questionnaire_id` bigint NOT NULL,
  `section_id` bigint DEFAULT NULL,
  PRIMARY KEY (`questionnaire_question_id`),
  UNIQUE KEY `uqQqQuestionnaireQuestion` (`questionnaire_id`,`question_id`),
  KEY `idxQqQuestion` (`question_id`),
  KEY `idxQqSection` (`section_id`),
  CONSTRAINT `fkQqQuestion` FOREIGN KEY (`question_id`) REFERENCES `question` (`question_id`),
  CONSTRAINT `fkQqQuestionnaire` FOREIGN KEY (`questionnaire_id`) REFERENCES `questionnaire` (`questionnaire_id`),
  CONSTRAINT `fkQqSection` FOREIGN KEY (`section_id`) REFERENCES `section` (`section_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `respondent_assessment_mapping` (
  `respondent_assessment_mapping_id` bigint NOT NULL AUTO_INCREMENT,
  `assessment_status` enum('COMPLETED','NOT_STARTED','ONGOING') NOT NULL,
  `is_persisted` bit(1) NOT NULL,
  `assessment_id` bigint NOT NULL,
  `respondent_user_id` bigint NOT NULL,
  PRIMARY KEY (`respondent_assessment_mapping_id`),
  UNIQUE KEY `uqRamRespondentAssessment` (`respondent_user_id`,`assessment_id`),
  KEY `idxRamAssessment` (`assessment_id`),
  CONSTRAINT `fkRamAssessment` FOREIGN KEY (`assessment_id`) REFERENCES `assessment` (`assessment_id`),
  CONSTRAINT `fkRamRespondent` FOREIGN KEY (`respondent_user_id`) REFERENCES `respondent_user` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `respondent_user` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `consented_at` datetime(6) DEFAULT NULL,
  `gender` enum('FEMALE','MALE','OTHER') DEFAULT NULL,
  `is_consented` bit(1) NOT NULL,
  `name` varchar(255) DEFAULT NULL,
  `phone` varchar(255) DEFAULT NULL,
  `organization_id` bigint DEFAULT NULL,
  `user_id` bigint NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uqRespondentUserUser` (`user_id`),
  KEY `fkRespondentUserOrganization` (`organization_id`),
  CONSTRAINT `fkRespondentUserOrganization` FOREIGN KEY (`organization_id`) REFERENCES `organization` (`organization_id`),
  CONSTRAINT `fkRespondentUserUser` FOREIGN KEY (`user_id`) REFERENCES `User` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `role` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `description` text,
  `name` varchar(50) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uqRoleName` (`name`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `role_group` (
  `role_group_id` bigint NOT NULL AUTO_INCREMENT,
  `description` text,
  `name` varchar(50) NOT NULL,
  PRIMARY KEY (`role_group_id`),
  UNIQUE KEY `uqRoleGroupName` (`name`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `role_group_role` (
  `role_group_id` bigint NOT NULL,
  `role_id` bigint NOT NULL,
  PRIMARY KEY (`role_group_id`,`role_id`),
  KEY `fkRoleGroupRoleRole` (`role_id`),
  CONSTRAINT `fkRoleGroupRoleGroup` FOREIGN KEY (`role_group_id`) REFERENCES `role_group` (`role_group_id`),
  CONSTRAINT `fkRoleGroupRoleRole` FOREIGN KEY (`role_id`) REFERENCES `role` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `role_url_path` (
  `role_id` bigint NOT NULL,
  `url_path` varchar(255) NOT NULL,
  PRIMARY KEY (`role_id`,`url_path`),
  CONSTRAINT `fkRoleUrlPathRole` FOREIGN KEY (`role_id`) REFERENCES `role` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `section` (
  `section_id` bigint NOT NULL AUTO_INCREMENT,
  `instruction` text,
  `name` varchar(200) NOT NULL,
  `questionnaire_id` bigint NOT NULL,
  PRIMARY KEY (`section_id`),
  KEY `idxSectionQuestionnaire` (`questionnaire_id`),
  CONSTRAINT `fkSectionQuestionnaire` FOREIGN KEY (`questionnaire_id`) REFERENCES `questionnaire` (`questionnaire_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

SET FOREIGN_KEY_CHECKS = 1;
