-- Direct computation mode: let an all-EXPRESSION computation deliver a report
-- without generated code, an LLM or the sandbox.
--
-- See docs/direct-computation-mode.md. Two columns' worth of change and one
-- backfill; the engine it turns on already exists (ReportDryRunService already
-- evaluates every rule over every respondent — only the last mile to a PDF was
-- missing, and that was a missing BINDING, not a missing evaluator).
--
--   report_computation.mode            DIRECT | GENERATED
--   report_tag_binding.report_computation_id / output_key
--                                      what a VALUE tag is filled from
--
-- Why `mode` sits on the computation and not on each binding: a report with
-- half its tags evaluated in Java and half written by generated Python has two
-- provenances and one audit trail. When a number is wrong nobody could say
-- which engine produced it. A computation is wholly one or the other.
--
-- Why the binding stores (computation, output_key) rather than a rule id: the
-- shape is then IDENTICAL in both modes — in DIRECT the output key is the slug
-- of a rule pinned into that computation, in GENERATED it is a key the
-- generated function declares. A template bound today keeps working when its
-- computation is later regenerated by AI. No re-binding, no second migration.
--
-- Deliberately absent, each a decision:
--
--   * No FK from report_tag_binding to report_computation. A template is
--     PORTABLE — the same counselling layout serves many assessments — while a
--     computation is bound to one. An FK would make deleting a computation
--     depend on every template that once referenced it. The pairing is checked
--     in the service at publish and at approve, where both sides are known.
--   * No report_computation_version table. DIRECT mode's artifact IS the pinned
--     report_rule_version rows, which are already immutable and already
--     referenced by report_computation_rule. A version row holding no artifact
--     would be the guessed-shape table V27 declined to create.
--   * No new status value. STATUS_APPROVED already exists as a constant in
--     ReportComputation and was simply unreachable; this migration is what
--     makes it reachable, and that needs no schema change.
--
-- Guarded per column (errno 1060) with the prepared-statement pattern V28
-- established: MySQL commits DDL implicitly and cannot roll it back, so a
-- re-run after a partial apply has to be a no-op rather than merely unlikely.

-- ── report_computation.mode ─────────────────────────────────────────────────
-- Added NULL, backfilled, then tightened — the CLAUDE.md rule. A NOT NULL
-- DEFAULT would have stamped every existing row with whichever value we picked,
-- which is a CLAIM about those rows' rules. We can read the rules instead.
SET @col_exists := (
    SELECT COUNT(*) FROM information_schema.COLUMNS
    WHERE TABLE_SCHEMA = DATABASE()
      AND TABLE_NAME   = 'report_computation'
      AND COLUMN_NAME  = 'mode'
);
SET @ddl := IF(@col_exists > 0, 'SELECT 1',
    'ALTER TABLE `report_computation` ADD COLUMN `mode` VARCHAR(16) DEFAULT NULL AFTER `status`');
PREPARE stmt FROM @ddl; EXECUTE stmt; DEALLOCATE PREPARE stmt;

-- Backfill from the data, not from a guess: a computation is DIRECT exactly
-- when nothing pinned into it needs prose. NOT EXISTS rather than a join so a
-- computation with no rules yet (a fresh DRAFT) resolves to DIRECT, which is
-- also the right answer — it has nothing that needs generating.
UPDATE `report_computation` c
   SET c.`mode` = CASE WHEN NOT EXISTS (
           SELECT 1
             FROM `report_computation_rule` cr
             JOIN `report_rule_version` rv
               ON rv.`report_rule_version_id` = cr.`report_rule_version_id`
            WHERE cr.`report_computation_id` = c.`report_computation_id`
              AND rv.`definition_kind` <> 'EXPRESSION'
       ) THEN 'DIRECT' ELSE 'GENERATED' END
 WHERE c.`mode` IS NULL;

ALTER TABLE `report_computation` MODIFY `mode` VARCHAR(16) NOT NULL;

-- ── report_tag_binding.report_computation_id ────────────────────────────────
SET @col_exists := (
    SELECT COUNT(*) FROM information_schema.COLUMNS
    WHERE TABLE_SCHEMA = DATABASE()
      AND TABLE_NAME   = 'report_tag_binding'
      AND COLUMN_NAME  = 'report_computation_id'
);
SET @ddl := IF(@col_exists > 0, 'SELECT 1',
    'ALTER TABLE `report_tag_binding` ADD COLUMN `report_computation_id` BIGINT DEFAULT NULL AFTER `literal_text`');
PREPARE stmt FROM @ddl; EXECUTE stmt; DEALLOCATE PREPARE stmt;

-- ── report_tag_binding.output_key ───────────────────────────────────────────
-- 80 to match report_rule.slug: in DIRECT mode this holds one.
SET @col_exists := (
    SELECT COUNT(*) FROM information_schema.COLUMNS
    WHERE TABLE_SCHEMA = DATABASE()
      AND TABLE_NAME   = 'report_tag_binding'
      AND COLUMN_NAME  = 'output_key'
);
SET @ddl := IF(@col_exists > 0, 'SELECT 1',
    'ALTER TABLE `report_tag_binding` ADD COLUMN `output_key` VARCHAR(80) DEFAULT NULL AFTER `report_computation_id`');
PREPARE stmt FROM @ddl; EXECUTE stmt; DEALLOCATE PREPARE stmt;

-- Resolving a report reads every binding of one template and asks each one
-- which computation it points at. Not unique: two tags legitimately draw two
-- different output keys from the same computation.
SET @idx_exists := (
    SELECT COUNT(*) FROM information_schema.STATISTICS
    WHERE TABLE_SCHEMA = DATABASE()
      AND TABLE_NAME   = 'report_tag_binding'
      AND INDEX_NAME   = 'idxRtbComputation'
);
SET @ddl := IF(@idx_exists > 0, 'SELECT 1',
    'ALTER TABLE `report_tag_binding` ADD KEY `idxRtbComputation` (`report_computation_id`)');
PREPARE stmt FROM @ddl; EXECUTE stmt; DEALLOCATE PREPARE stmt;
