services:
  nginx:
    image: nginx:latest
    container_name: bodhassess-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./conf.d:/etc/nginx/conf.d:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro
      - /var/www/certbot:/var/www/certbot:ro
    networks:
      - bodhpsychometric

networks:
  bodhpsychometric:
    name: bodhassess-api_bodhpsychometric
    external: true
